### *lista de 10* ###

In [2]:
### ** Hola ** ###
lista=list(range(1,11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

### *lista y np* ###

In [4]:
import numpy as np
arreglo=np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### *Corroborar la estructura* ###

In [6]:
arreglo.dtype

dtype('int32')

### *Definir array y float32* ###

In [7]:
np.array(arreglo, dtype=np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

### *arreglo de uno* ###

In [17]:
arreglo_de_unos=np.ones(10)
arreglo_de_unos


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
arreglos_de_zeros=np.zeros(5)
arreglos_de_zeros

array([0., 0., 0., 0., 0.])

In [9]:
arreglo_de_unos.astype(int)
arreglo_de_unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### *arreglo randoms* ###

In [22]:
areglo_random=np.random.rand(2,1) #rand y randint
areglo_random

array([[0.67206683],
       [0.39602811]])

In [24]:
arreglo_mas_r=np.random.randint(1,5,(2,5)) # el penultimo elemento hace repeticiones del proseso, perro el ultimo finl es para numero de elementos (1,5,2)
arreglo_mas_r

array([[2, 3, 2, 3, 1],
       [3, 3, 4, 4, 2]])